# Generated by Django 5.1.4 on 2024-12-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
