# Generated by Django 3.2 on 2024-10-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('cupo', models.IntegerField()),
            ],
        ),
    ]
