# Generated by Django 3.2 on 2024-10-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appConcierto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='hora',
            field=models.TimeField(),
        ),
    ]
