# Generated by Django 3.2 on 2024-11-15 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCliente', '0001_initial'),
        ('appConcierto', '0002_alter_concierto_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('area_designada', models.CharField(max_length=50)),
                ('fecha_reserva', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCliente.cliente')),
                ('id_concierto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appConcierto.concierto')),
            ],
        ),
    ]
