# Generated by Django 3.2 on 2024-11-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEntrada', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='id_entrada',
            new_name='id',
        ),
    ]
